---
- name: Check if IUS repo is already configured
  stat:
    path: /etc/yum.repos.d/ius.repo
  register: ius_repofile_result

- name: Configure IUS variables
  set_fact:
    ius_distribution_abbrev: "{{ (ansible_distribution == 'CentOS') | ternary('centos', 'rhel') }}"

- name: Install IUS repo
  yum:
    name: |
      https://{{ ius_distribution_abbrev }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm
    state: present
  when: not ius_repofile_result.stat.exists

# Disable GPG Check on IUS repositories
- lineinfile:
    path: /etc/yum.repos.d/ius-archive.repo
    regexp: '^gpgcheck\s*=\s*1'
    line: 'gpgcheck = 0'
- lineinfile:
    path: /etc/yum.repos.d/ius-archive.repo
    regexp: '^gpgcheck\s*=\s*1'
    line: 'gpgcheck = 0'
- lineinfile:
    path: /etc/yum.repos.d/ius-archive.repo
    regexp: '^gpgcheck\s*=\s*1'
    line: 'gpgcheck = 0'
- lineinfile:
    path: /etc/yum.repos.d/ius.repo
    regexp: '^gpgcheck\s*=\s*1'
    line: 'gpgcheck = 0'
- lineinfile:
    path: /etc/yum.repos.d/ius.repo
    regexp: '^gpgcheck\s*=\s*1'
    line: 'gpgcheck = 0'
- lineinfile:
    path: /etc/yum.repos.d/ius.repo
    regexp: '^gpgcheck\s*=\s*1'
    line: 'gpgcheck = 0'

- name: Import IUS GPG key
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7
    state: present
  when: not ius_repofile_result.stat.exists
